name: CI-SFTP

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.SSH_USER }}
          server: ${{ secrets.SSH_SERVER }}
          port: ${{ secrets.SSH_SERVER_PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

          local_path: ./* # On Github
          remote_path: ${{ secrets.REMOTE_PATH }} # On server
          delete_remote_files: true
          # sftp args
          args: "-o ConnectTimeout=5"

      - name: Write SSH private key to file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/private_key.pem
          chmod 600 /tmp/private_key.pem

      - name: Restart Docker container
        run: |
          ssh -i /tmp/private_key.pem -o StrictHostKeyChecking=no -p ${{ secrets.SSH_SERVER_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} 'docker restart <bettercal_nginx>'

      - name: Clean up SSH private key
        run: |
          rm /tmp/private_key.pem
